services:
  usuario.listener.usuarios:
    class: Usuario\UsuarioBundle\EventListener\UsuariosListener
    arguments: [ '@service_container' ]
    tags:
      - { name: doctrine.event_listener, event: prePersist }
      - { name: doctrine.event_listener, event: preUpdate }
