<?php

namespace Usuario\UsuarioBundle\Repository;

/**
 * TipoUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllTipoUsuarios()
    {
        $qb = $this->createQueryBuilder('t');
        $qb->orderBy('t.tipoUsuario', 'ASC');
        return $qb;
    }
}
