<?php

namespace Establecimiento\EstablecimientoBundle\Repository;

/**
 * ActuacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActuacionRepository extends \Doctrine\ORM\EntityRepository
{
	public function checkActuacionExciste(\Establecimiento\EstablecimientoBundle\Entity\Actuacion $actuacion)
    {
		$qb = $this->createQueryBuilder('a')  
	        ->where('a.tipo = :tipo', 'a.numero = :numero','a.reparticion = :reparticion', 'a.anio = :anio','a.establecimiento != :establecimiento')
	        ->setParameter('tipo', $actuacion->getTipo()->getId())
	        ->setParameter('numero', $actuacion->getNumero())
	        ->setParameter('reparticion',$actuacion->getReparticion()->getId())
	        ->setParameter('anio',$actuacion->getAnio())
	        ->setParameter('establecimiento', $actuacion->getEstablecimiento()->getId())
	        ->getQuery();

	    $actuaciones = $qb->getResult();

    	if(count($actuaciones) == 0){
    		return false;
    	}else{
    		return true;
    	}  
    }

    public function searchAllActuacion($idEstablecimiento){
    	$qb = $this->createQueryBuilder('a')
    	->where('a.idEstablecimiento = :idEstablecimiento ')
    	->setParameter('idEstablecimiento',$idEstablecimiento);
        return $qb;
    }
}
