<?php

namespace Establecimiento\EstablecimientoBundle\Repository;

/**
 * EstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActuacionTipoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllTipos()
    {
        $qb = $this->createQueryBuilder('e');
        $qb->orderBy('e.tipo', 'ASC');
        return $qb;
    }

}
