<?php

namespace Establecimiento\EstablecimientoBundle\Repository;

/**
 * CallesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallesRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllCalles()
    {
	    $qb = $this->createQueryBuilder('c');
        $qb->orderBy('c.calle', 'ASC');
        
        return $qb;
	}

	public function findAllCallesArray()
    {
	    $qb = $this->createQueryBuilder('c')
	    ->select('c.id, c.calle');
        $qb->orderBy('c.calle', 'ASC');                
        
        return $qb->getQuery()->getResult();
	}
}
