<?php

namespace Establecimiento\EstablecimientoBundle\Repository;

/**
 * destinoVuelcoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinoVuelcoRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllDestinoVuelco()
    {
	    $qb = $this->createQueryBuilder('d');
        $qb->orderBy('d.destinoVuelco', 'ASC');
        return $qb;
	}
}
