<?php

namespace Establecimiento\EstablecimientoBundle\Repository;

/**
 * DireccionRSRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DireccionRSRepository extends \Doctrine\ORM\EntityRepository
{
}
