<?php

namespace Establecimiento\EstablecimientoBundle\Repository;

/**
 * DireccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DireccionRepository extends \Doctrine\ORM\EntityRepository
{
	public function checkDireccionExiste(\Establecimiento\EstablecimientoBundle\Entity\Direccion $direccion)
    {
    	$qb = $this->createQueryBuilder('d')
                   ->where('d.calle = :calle and d.altura = :altura and d.establecimiento <> :establecimiento');

        $piso = $direccion->getPiso();
        if(is_null($piso)){
            $qb->andWhere("(d.piso is NULL or d.piso = '')");
        }else{
            $qb->andWhere('d.piso = :piso')
            ->setParameter('piso',$direccion->getPiso());            
        }

        $dpto = $direccion->getDpto();
        if(is_null($dpto)){
            $qb->andWhere("(d.dpto is NULL or d.dpto = '')");
        }else{
            $qb->andWhere('d.dpto = :dpto')
            ->setParameter('dpto',$direccion->getdpto());            
        }

        $local = $direccion->getLocal();
        if(is_null($local)){
            $qb->andWhere("(d.local is NULL or d.local = '')");
        }else{
            $qb->andWhere('d.local = :local')
            ->setParameter('local',$direccion->getLocal());            
        }
        $qb->setParameter('calle',$direccion->getCalle()->getId())
           ->setParameter('altura', $direccion->getAltura())
           ->setParameter('establecimiento', $direccion->getEstablecimiento()->getId());	        

    	$direcciones = $qb->getQuery()->getResult();
    	
    	if(count($direcciones) == 0){
    		return false;
    	}else{
    		return true;
    	}    	
    }

    public function buscarDireccionExacta($direccion)
    {
        $qb = $this->createQueryBuilder('d')
        ->where('d.calle = :calle and d.altura = :altura');        

        $piso = $direccion->getPiso();

        if(is_null($piso) || trim($piso) == '0' || trim($piso) == ''){            
            $qb->andWhere("(d.piso is NULL or TRIM(d.piso) = '' or d.piso = 0)");
        }else{            
            $qb->andWhere('d.piso = :piso')
            ->setParameter('piso',$direccion->getPiso());
        }

        $dpto = $direccion->getdpto();
        if(is_null($dpto) || trim($dpto) == '0' || trim($dpto) == ''){
            $qb->andWhere("(d.dpto is NULL or TRIM(d.dpto) = '' or d.dpto = 0)");
        }else{
            $qb->andWhere('d.dpto = :dpto')
            ->setParameter('dpto',$direccion->getdpto());            
        }

        $local = $direccion->getLocal();
        if(is_null($local) || trim($local) == '0' || trim($local) == ''){
            $qb->andWhere("(d.local is NULL or TRIM(d.local) = '' or d.local = 0)");
        }else{
            $qb->andWhere('d.local = :local')
            ->setParameter('local',$direccion->getLocal());
        }
        $qb->setParameter('calle',$direccion->getCalle()->getId())
           ->setParameter('altura', $direccion->getAltura());
        
        return $qb->getQuery()->getResult();
    }      
}
