<?php

namespace Establecimiento\EstablecimientoBundle\Repository;

/**
 * EstablecimientoRazonSocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstablecimientoRazonSocialRepository extends \Doctrine\ORM\EntityRepository
{
}
