<?php

namespace Establecimiento\EstablecimientoBundle\Repository;

/**
 * EstadoRes326Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoRes326Repository extends \Doctrine\ORM\EntityRepository
{
	public function findAllEstadosRes()
    {
	    $qb = $this->createQueryBuilder('e');
        $qb->orderBy('e.estadoRes326', 'ASC');        
        return $qb;
	}
}
