<?php

namespace Establecimiento\EstablecimientoBundle\Repository;

/**
 * HistorialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistorialRepository extends \Doctrine\ORM\EntityRepository
{
	public function getHistorial($id,$tabla){
      $qb = $this->createQueryBuilder('h')    
    	->where('h.idTabla = :id and h.tabla = :tabla')
    	->orderBy('h.fecha', 'DESC')
    	->setParameter('id', $id)
    	->setParameter('tabla', $tabla);

    	return $qb->getQuery()->getResult();
    }

    public function getHistorialUsuario($id){
    	$qb = $this->createQueryBuilder('h')    
    	->where('h.usuarioMotificador = :id')
    	->orderBy('h.fecha', 'DESC')
    	->setParameter('id', $id);    	

    	return $qb->getQuery()->getResult();
    }
}
