<?php

namespace Establecimiento\EstablecimientoBundle\Repository;

/**
 * RazonSocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RazonSocialRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllRazonesSociales($rz = array(),$limit = null)
    {   
        $qb = $this->createQueryBuilder('r');
        $qb->orderBy('r.cuit', 'ASC');


        if(count($rz) > 0){
            $qb->where('r.id in (:list)')
            ->setParameter('list',$rz);
        }

        if($limit){
            $qb->setMaxResults($limit);
        }

        return $qb;
	}

    public function findRazonesSocialesFront($search)
    {
        $qb = $this->createQueryBuilder('r')
        ->select("r.id as id,CONCAT(r.nombre1,' ',COALESCE(r.nombre2,''),' CUIT: ',r.cuit) as name")
        ->orderBy('r.cuit', 'ASC')
        ->where("CONCAT(r.nombre1,' ',COALESCE(r.nombre2,''),r.cuit) like '%".str_replace(' ','%',$search)."%'")
        ->setMaxResults(50);
        
        return $qb->getQuery()->getResult();
    }

    public function findRazonesSocialesTableFront($search)
    {
        $qb = $this->createQueryBuilder('r')
        ->select("CONCAT(r.nombre1,' ',COALESCE(r.nombre2,'')) as id,CONCAT(r.nombre1,' ',COALESCE(r.nombre2,''),' CUIT: ',r.cuit) as name")
        ->orderBy('r.cuit', 'ASC')
        ->where("CONCAT(r.nombre1,' ',COALESCE(r.nombre2,''),r.cuit) like '%".str_replace(' ','%',$search)."%'")
        ->setMaxResults(50);
        
        return $qb->getQuery()->getResult();
    }

	public function selectRazonSocialTabla()
    {
		$em=$this->getEntityManager();
		$dql="SELECT CONCAT(COALESCE(r.nombre1,''),' ',COALESCE(r.nombre2,'')) as razonessociales FROM EstablecimientoEstablecimientoBundle:RazonSocial r";
    	$consulta=$em->createQuery($dql);	

        return $consulta->getResult();
    }	
}
