<?php

namespace Establecimiento\EstablecimientoBundle\Repository;

/**
 * ReparticionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReparticionRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllReparticiones()
    {
	    $qb = $this->createQueryBuilder('r');        
        $qb->orderBy('r.reparticion', 'ASC');
                 
        //return $qb->getQuery()->getResult();
        return $qb;
	}

	public function findAllReparticionesForDispoClausura()
    {
	    $qb = $this->createQueryBuilder('r');        
        $qb->orderBy('r.reparticion', 'ASC')
        ->where('r.id in (1,8,35) ');
                 
        //return $qb->getQuery()->getResult();
        return $qb;
	}
}
