<?php

namespace Establecimiento\EstablecimientoBundle\Repository;

/**
 * ResultadosUltimaInspeccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadosUltimaInspeccionRepository extends \Doctrine\ORM\EntityRepository
{	
}
