<?php

namespace Establecimiento\EstablecimientoBundle\Repository;

/**
 * RubroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RubroRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllRubro()
    {
	    $qb = $this->createQueryBuilder('r');  
        $qb->orderBy('r.codigo', 'ASC');        
        return $qb;
	}

	public function selectRubrosTabla()
    {
		$em=$this->getEntityManager();
		$dql="SELECT r.rubro FROM EstablecimientoEstablecimientoBundle:Rubro r";
    	$consulta=$em->createQuery($dql);	

        return $consulta->getResult();
    }
}
