<?php

namespace Establecimiento\EstablecimientoBundle\Repository;

/**
 * TipoTratamientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoTratamientoRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllTipoTratamiento()
    {
	    $qb = $this->createQueryBuilder('t');
        $qb->orderBy('t.tipoTratamiento', 'ASC');        
        return $qb;
	}
}
