<?php

namespace Establecimiento\EstablecimientoBundle\Repository;

/**
 * TipoResiduosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoResiduosRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllTipoResiduos()
    {
	    $qb = $this->createQueryBuilder('t');
        $qb->orderBy('t.codigoResiduo', 'ASC');        
        return $qb;
	}
}
