<?php

namespace Establecimiento\EstablecimientoBundle\Repository;

/**
 * TipoActuacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoActuacionRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllTipos()
    {
	    $qb = $this->createQueryBuilder('t');        
        $qb->orderBy('t.tipoActuacion', 'ASC');
                 
        //return $qb->getQuery()->getResult();
        return $qb;
	}
}
