<?php

namespace Inspecciones\InspeccionesBundle\Repository;

/**
 * AmbientesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmbientesRepository extends \Doctrine\ORM\EntityRepository
{
}
