<?php

namespace Inspecciones\InspeccionesBundle\Repository;

/**
 * CorrecionRuidosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorrecionRuidosRepository extends \Doctrine\ORM\EntityRepository
{
}
