<?php

namespace Inspecciones\InspeccionesBundle\Repository;

/**
 * DenuncianteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DenuncianteRepository extends \Doctrine\ORM\EntityRepository
{
}
