<?php

namespace Inspecciones\InspeccionesBundle\Repository;

/**
 * DireccionProvisoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DireccionProvisoriaRepository extends \Doctrine\ORM\EntityRepository
{
}
