<?php

namespace Inspecciones\InspeccionesBundle\Repository;

/**
 * EquipoRuidosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipoRuidosRepository extends \Doctrine\ORM\EntityRepository
{
}
