<?php

namespace Inspecciones\InspeccionesBundle\Repository;

/**
 * InspeccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InspeccionRepository extends \Doctrine\ORM\EntityRepository
{	
}
