<?php

namespace Inspecciones\InspeccionesBundle\Repository;

/**
 * MotivoInspeccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotivoInspeccionRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllMotivos()
    {
	    $qb = $this->createQueryBuilder('m');        
        $qb->orderBy('m.motivo', 'ASC');
        return $qb;
	}
}
