<?php

namespace Inspecciones\InspeccionesBundle\Repository;

/**
 * MotivosReInspeccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotivosReInspeccionRepository extends \Doctrine\ORM\EntityRepository
{
}
