<?php

namespace Inspecciones\InspeccionesBundle\Repository;

/**
 * ResultadosFotosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadosFotosRepository extends \Doctrine\ORM\EntityRepository
{
}
