<?php

namespace Inspecciones\InspeccionesBundle\Repository;

/**
 * ResultadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultadosRepository extends \Doctrine\ORM\EntityRepository
{
	public function tieneCedulaInmediata($idOrdenInspeccion)
    {
        $qb = $this->createQueryBuilder('r')
        ->where('r.grupo = 18 AND r.pregunta = 355 AND r.ordenInspeccion = :idOrdenInspeccion')
        ->setParameter('idOrdenInspeccion',$idOrdenInspeccion)
        ;
    }
}
