<?php

namespace Inspecciones\InspeccionesBundle\Repository;

/**
 * RuidosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RuidosRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllRuidos()
    {
        $qb = $this->createQueryBuilder('z');
        return $qb->getQuery()->getResult();
    }
}
