<?php

namespace Inspecciones\InspeccionesBundle\Repository;

/**
 * VibracionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VibracionesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllVibracion()
    {
        $qb = $this->createQueryBuilder('v');
        $qb->orderBy('v.idVibraciones', 'ASC');
        return $qb->getQuery()->getResult();
    }
}
