services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    app.login_listener:
        class: Usuario\UsuarioBundle\Listener\LoginListener
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }
            - { name: kernel.event_listener, event: kernel.request, priority: 9 }

    app.twig_extension:
        class: CoreBundle\Logic\AppExtension
        public: false
        tags:
            - { name: twig.extension }

    app.cors_listener:
        arguments: [%CORS_ALLOW_ORIGIN%]
        class: CoreBundle\Logic\CorsListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    AppBundle\:
        resource: '../../src/AppBundle/*'
        public: true

    AppBundle\EventListener\AccessControllerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }
            - { name: kernel.event_listener, event: kernel.terminate }

    AppBundle_Logout:
        class: AppBundle\EventListener\LogoutListener

    AppBundle\Handler\SessionIdleHandler:
        arguments: [%session_max_idle_time%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    AppBundle\Service\JwtAuth:
        class: AppBundle\Service\JwtAuth

