<?php

namespace Notificaciones\NotificacionesBundle\Repository;

/**
 * CedulaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CedulaRepository extends \Doctrine\ORM\EntityRepository
{
	public function findremitoCedulas($fechaIncial,$fechaFinal)
    {
    
        $fechaInicial = date("Y-m-d", strtotime($fechaIncial));
        $fechaFinal = date("Y-m-d", strtotime($fechaFinal));


        $em=$this->getEntityManager();
        $dql="SELECT c.numero,tc.tipoCedula,noti.fechaEnvioFirma,noti.direccionNotificada
            FROM NotificacionesNotificacionesBundle:Cedula c
            JOIN c.tipo tc
            JOIN c.notificacion noti
            WHERE noti.fechaEnvioFirma BETWEEN '".$fechaInicial."' AND '".$fechaFinal."' 
            ORDER BY noti.fechaEnvioFirma DESC";
  
        $consulta=$em->createQuery($dql);   
        
       /* print_r($consulta->getResult());
        exit();*/
        return $consulta->getResult();
	}

    public function maxCedula()
    {
        $qb = $this->createQueryBuilder('c')
        ->select('MAX(c.numero)')       
        ->orderBy('c.numero', 'ASC');
                 
        return $qb->getQuery()->getResult();
        //return $qb;
    }

    public function cedulasxEstablecimiento($idEstablecimiento)
    {
        $qb = $this->createQueryBuilder('c')
        ->join('c.notificacion','n')
        ->where('n.establecimiento = :idEstablecimiento and n.estado > 4 and n.estado != 11 and n.fechaNotificacion is not null')
        ->orderBy('n.fechaNotificacion', 'DESC')
        ->setParameter('idEstablecimiento', $idEstablecimiento)
        ->setMaxResults(1)
        ;

        return  $qb->getQuery()->getResult();
    }
}
