<?php

namespace Notificaciones\NotificacionesBundle\Repository;

/**
 * ControladoresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControladorRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllControladores()
    {
	    $qb = $this->createQueryBuilder('c');
        $qb->orderBy('c.apellido', 'ASC');
                 
        //return $qb->getQuery()->getResult();
        return $qb;
	}
}
