<?php

namespace Notificaciones\NotificacionesBundle\Repository;

/**
 * DisposicionClausuraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisposicionClausuraRepository extends \Doctrine\ORM\EntityRepository
{
	public function searchClausura($idEstablecimiento)
    {
	    $qb = $this->createQueryBuilder('dc')
	    ->join('dc.disposicion', 'd')
	    ->join('d.notificacion','n')
        ->where('n.establecimiento = :establecimiento and (dc.levantada = 0 or dc.levantada is null )')
        ->setParameter('establecimiento', $idEstablecimiento)
        ;
                 
        return $qb->getQuery()->getResult();        
	}
}
