<?php

namespace Notificaciones\NotificacionesBundle\Repository;

/**
 * DisposicionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisposicionRepository extends \Doctrine\ORM\EntityRepository
{
	public function disposicionesxEstablecimiento($idEstablecimiento)
    {
    	$query = 'SELECT d.id from disposicion as d
                INNER JOIN notificacion as n on d.id = n.id
                WHERE n.estado_id > 4 and n.estado_id != 11 and n.establecimiento_id ='.$idEstablecimiento;

	    $stmt = $this->getEntityManager()->getConnection()->prepare($query);
	    $stmt->execute();
	    return $stmt->fetchAll();       
    }

    public function disposicionesxId($id)
    {    
        $query = 'SELECT * from disposicion as d                
                WHERE d.id='.$id;

	    $stmt = $this->getEntityManager()->getConnection()->prepare($query);
	    $stmt->execute();
	    return $stmt->fetchAll();

    }  
}
