<?php

namespace Notificaciones\NotificacionesBundle\Repository;

/**
 * EstadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoRepository extends \Doctrine\ORM\EntityRepository
{
	public function findEstadosForCedula()
    {
	    $qb = $this->createQueryBuilder('e');
        $qb->where('e.id <> 4');
        $qb->orderBy('e.estado', 'ASC');
        
                 
        //return $qb->getQuery()->getResult();
        return $qb;
	}

    public function selectEstadoTabla()
    {
        $em=$this->getEntityManager();
        $dql="SELECT r.estado FROM NotificacionesNotificacionesBundle:Estado r WHERE r.id <> 4";
        $consulta=$em->createQuery($dql);   

        return $consulta->getResult();
    }
}
