<?php

namespace Notificaciones\NotificacionesBundle\Repository;

/**
 * LeyesClausuraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeyesClausuraRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllLeyes()
    {
	    $qb = $this->createQueryBuilder('a');
        $qb->orderBy('a.ley', 'ASC');
        
                 
        //return $qb->getQuery()->getResult();
        return $qb;
	}
}
