<?php

namespace Notificaciones\NotificacionesBundle\Repository;

/**
 * TipoCedulaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoCedulaRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllTipos()
    {
	    $qb = $this->createQueryBuilder('t');
        $qb->orderBy('t.tipoCedula', 'ASC');
                 
        //return $qb->getQuery()->getResult();
        return $qb;
	}

	public function findAllTiposArray()
    {
	    $qb = $this->createQueryBuilder('t')
        ->select('t.id, t.tipoCedula');
        $qb->orderBy('t.tipoCedula', 'ASC');
                 
        return $qb->getQuery()->getResult();        
	}

    public function selectTipoCedulaTabla()
    {
        $em=$this->getEntityManager();
        $dql="SELECT r.tipoCedula FROM NotificacionesNotificacionesBundle:TipoCedula r";
        $consulta=$em->createQuery($dql);   

        return $consulta->getResult();
    }
}
