<?php

namespace Notificaciones\NotificacionesBundle\Repository;

/**
 * TipoDispoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDispoRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllTipos($tipo = null)
    {       

	    $qb = $this->createQueryBuilder('t');
        $qb->orderBy('t.tipoDispo', 'ASC');

        if($tipo == 1){
            $qb->where('t.id in (4,5,1,8,10)');
        }
        if($tipo == 2){
            $qb->where('t.id in (6,7,2,3,9,11)');
        } 

        //return $qb->getQuery()->getResult();
        return $qb;
	}

    public function selectTipoDisposicionTabla()
    {
        $em=$this->getEntityManager();
        $dql="SELECT r.tipoDispo FROM NotificacionesNotificacionesBundle:tipoDispo r";
        $consulta=$em->createQuery($dql);   

        return $consulta->getResult();
    }
}
