<?php

namespace Encuesta\EncuestaBundle\Repository;

/**
 * FaltaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaltaRepository extends \Doctrine\ORM\EntityRepository
{
}
