<?php

namespace Encuesta\EncuestaBundle\Repository;

/**
 * GrupoPreguntasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoPreguntasRepository extends \Doctrine\ORM\EntityRepository
{
}
