<?php

namespace Encuesta\EncuestaBundle\Repository;

/**
 * ModeloEncuestaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModeloEncuestaRepository extends \Doctrine\ORM\EntityRepository
{
}
