<?php

namespace Encuesta\EncuestaBundle\Repository;

/**
 * RequisitosPreguntaGrupoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequisitosPreguntaGrupoRepository extends \Doctrine\ORM\EntityRepository
{
}
