<?php

namespace Encuesta\EncuestaBundle\Repository;

/**
 * SiguientePreguntaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiguientePreguntaRepository extends \Doctrine\ORM\EntityRepository
{
}
