<?php

namespace Laboratorio\PedidoBundle\Repository;

/**
 * CargaResultadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CargaResultadosRepository extends \Doctrine\ORM\EntityRepository
{
}
