<?php

namespace Laboratorio\PedidoBundle\Repository;

/**
 * DeterminacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeterminacionRepository extends \Doctrine\ORM\EntityRepository
{
	public function getDeterminacionesForResultados($idMuestra,$idPrograma,$idArea)
	{		
		$qb = $this->createQueryBuilder('d')
	    ->innerJoin('d.programas','p')
	    ->leftjoin('LaboratorioPedidoBundle:CargaResultados','c','WITH','d.id = c.determinacion and c.muestra = :muestra')
	    ->where(' c.id is null  AND p.id = :programa AND d.area = :area')
	    ->setParameter('area', $idArea)
	    ->setParameter('programa', $idPrograma)
	    ->setParameter('muestra', $idMuestra)
	    ;
	    return $qb->getQuery()->getResult();  
	    
	}
}
