<?php

namespace Laboratorio\PedidoBundle\Repository;

/**
 * DeterminacionLegislacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeterminacionLegislacionRepository extends \Doctrine\ORM\EntityRepository
{
}
