<?php

namespace Laboratorio\PedidoBundle\Repository;

/**
 * EstadoMuestraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoMuestraRepository extends \Doctrine\ORM\EntityRepository
{
}
