<?php

namespace Laboratorio\PedidoBundle\Repository;

/**
 * HistorialCargaResultadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistorialCargaResultadosRepository extends \Doctrine\ORM\EntityRepository
{
}
