<?php

namespace Laboratorio\PedidoBundle\Repository;

/**
 * LegislacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegislacionRepository extends \Doctrine\ORM\EntityRepository
{
	public function getLegislacionToDeterminacion($idPrograma,$idDeterminacion,$idTipoDeterminacionLegislacion)
	{
		/*$qb = $this->createQueryBuilder('l')
	    ->innerJoin('l.programas','p')
	    ->innerJoin('p.determinaciones','d')
	    ->innerJoin('d.legislaciones','dl')
	    ->where(' p.id = :programa AND d.id = :determinacion AND (dl.tipo = :tipo OR dl.tipo = :tipo1)')
	    ->setParameter('programa', $idPrograma)
	    ->setParameter('determinacion', $idDeterminacion);*/

	    $qb = $this->createQueryBuilder('l')
	    ->innerJoin('LaboratorioPedidoBundle:DeterminacionLegislacion','dl','WITH','dl.legislacion = l')
	    ->innerJoin('l.programas','p')
	    ->where(' p.id = :programa AND dl.determinacion = :determinacion AND (dl.tipo = :tipo OR dl.tipo = :tipo1)')
	    ->setParameter('programa', $idPrograma)
	    ->setParameter('determinacion', $idDeterminacion);

	    if($idTipoDeterminacionLegislacion == 1 || $idTipoDeterminacionLegislacion == 4)
	    {
	    	$qb->setParameter('tipo', 1);
	    	$qb->setParameter('tipo1', 4);
	    }else{
	    	$qb->setParameter('tipo', $idTipoDeterminacionLegislacion);
	    	$qb->setParameter('tipo1', $idTipoDeterminacionLegislacion);
	    }

	    /*$a = $qb->getQuery();
	    $b = $a->getSql();
	    \Doctrine\Common\Util\Debug::dump($b);
	    exit();*/

	    
	    ;
	    return $qb;
	}
}