<?php

namespace Laboratorio\PedidoBundle\Repository;

/**
 * MuestraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MuestraRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMuestrasProtocolo1()
    {
        $qb = $this->createQueryBuilder('m');
        $qb->orderBy('m.idMuestra', 'DESC')
            ->where('m.autorizado = 1');
        return $qb;
    }

    public function findMuestraByNumero($numeroMuestra)
    {
        $qb = $this->createQueryBuilder('m');
        $qb->where('m.numeroMuestra = '.$numeroMuestra);

        /*$a = $qb->getQuery();
	    $b = $a->getSql();
	    \Doctrine\Common\Util\Debug::dump($b);
	    exit();*/

        return $qb->getQuery()->getResult();
    }

    public function findMuestrasPendientes ($anio)
    {
        $qb = $this->createQueryBuilder("m");
        $qb->orderBy("m.numeroMuestra", "DESC")
            ->where("m.autorizado = 0 AND m.fechaTomaMuestra > '".$anio."-01-01' AND m.fechaTomaMuestra < '".($anio)."-12-31'");

        return $qb->getQuery()->getResult();
    }
}
