<?php

namespace Laboratorio\PedidoBundle\Repository;

/**
 * MuestraEstadosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MuestraEstadosRepository extends \Doctrine\ORM\EntityRepository
{
}
