<?php

namespace Laboratorio\PedidoBundle\Repository;

/**
 * PrioridadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrioridadRepository extends \Doctrine\ORM\EntityRepository
{
}
