<?php

namespace Laboratorio\PedidoBundle\Repository;

/**
 * TipoDeterminacionLegislacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoDeterminacionLegislacionRepository extends \Doctrine\ORM\EntityRepository
{
}
