<?php

namespace Laboratorio\PedidoBundle\Repository;

/**
 * TipoPedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoPedidoRepository extends \Doctrine\ORM\EntityRepository
{
}
