<?php

namespace Faltas\FaltasBundle\Repository;

/**
 * ActaUtilizadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActaUtilizadaRepository extends \Doctrine\ORM\EntityRepository
{

    public function findActaUtilizadaByFechaArea($fechaInicial,$fechaFinal,$area = 0,$establecimiento = 0)
    {
        //$fecha = \DateTime::createFromFormat('Y-m-d', $fecha);
        $fechaInicial = date("Y-m-d", strtotime($fechaInicial));
        $fechaFinal = date("Y-m-d", strtotime($fechaFinal));

        if(!$fechaInicial){
            $fechaInicial = '1990-01-01';
        }

        if(!$fechaFinal || $fechaFinal == '1970-01-01'){
            $fechaFinal = '9999-12-31';
        }

        $qb = $this->createQueryBuilder('u')        
        ->join('u.acta','a')
        ->where('(a.estado = 2  )AND u.fechaRecepcion BETWEEN :fechainicial AND :fechafinal')
        ->setParameter('fechainicial',$fechaInicial)
        ->setParameter('fechafinal',$fechaFinal);

        if ($area!= 0){
            $qb->andWhere('u.areas = :area')
            ->setParameter('area',$area);
        }

        if($establecimiento != 0){
           $qb->join('a.ordenInspeccion','o') 
           ->join('o.establecimiento','e')
           ->andWhere('e.id = :idEstablecimiento')
           ->setParameter('idEstablecimiento',$establecimiento);
        }        

        return $qb->getQuery()->getResult();
    }

    public function findActaUtilizadaByFechaAreaProgramacion($fechaInicial,$fechaFinal,$area = 0,$establecimiento = 0)
    {
        //$fecha = \DateTime::createFromFormat('Y-m-d', $fecha);
        $fechaInicial = date("Y-m-d", strtotime($fechaInicial));
        $fechaFinal = date("Y-m-d", strtotime($fechaFinal));

        if(!$fechaInicial){
            $fechaInicial = '1990-01-01';
        }

        if(!$fechaFinal || $fechaFinal == '1970-01-01'){
            $fechaFinal = '9999-12-31';
        }

        $qb = $this->createQueryBuilder('u')        
        ->join('u.acta','a')
        ->where('(a.estado in (2,4,6)  )AND u.fechaRecepcion BETWEEN :fechainicial AND :fechafinal')
        ->setParameter('fechainicial',$fechaInicial)
        ->setParameter('fechafinal',$fechaFinal);

        if ($area!= 0){
            $qb->andWhere('u.areas = :area')
            ->setParameter('area',$area);
        }

        if($establecimiento != 0){
           $qb->join('a.ordenInspeccion','o') 
           ->join('o.establecimiento','e')
           ->andWhere('e.id = :idEstablecimiento')
           ->setParameter('idEstablecimiento',$establecimiento);
        }

        return $qb->getQuery()->getResult();
    }

    public function utilizadasEntreFecha($fechaInicial,$fechaFinal,$area)
    {
            $query = "SELECT count(*) FROM notificaciones.acta_utilizada where fechaInspeccion between '".$fechaInicial."' and '".$fechaFinal."' and areas_id =".$area;
            $stmt = $this->getEntityManager()->getConnection()->prepare($query);
            $stmt->execute();
            return $stmt->fetchAll();
    }
}
