<?php

namespace Faltas\FaltasBundle\Repository;

/**
 * AsignacionFajaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AsignacionFajaRepository extends \Doctrine\ORM\EntityRepository
{
	public function findNombreApellidobyIdFaja($faja)
    {
    	$em=$this->getEntityManager();

    	$dql="SELECT a.id,a.fechaAsignacion,CONCAT(u.apellido,', ',u.nombre) AS Nombre
    		FROM FaltasFaltasBundle:AsignacionFaja a
    		JOIN a.idUsuarioInspector u
    		JOIN a.faja f
    		WHERE f.id =:faja 
    		ORDER BY a.fechaAsignacion DESC";

    	$consulta=$em->createQuery($dql);
    	$consulta->setParameter('faja',$faja);		
	    
        return $consulta->getResult();
	}

    public function existeAsignacionxfechaApellidoyIdFaja($idUsuarioInspector,$fechaAsignacion,$idFaja)
    {
        $em=$this->getEntityManager();

        $dql="SELECT a
            FROM FaltasFaltasBundle:AsignacionActa a
            WHERE a.idUsuarioInspector=:idUsuarioInspector and a.fechaAsignacion=:fechaAsignacion and a.idFaja=:idFaja";

        $consulta=$em->createQuery($dql);
        $consulta->setParameter('idUsuarioInspector',$idUsuarioInspector);
        $consulta->setParameter('fechaAsignacion',$fechaAsignacion);      
        $consulta->setParameter('idFaja',$idFaja); 
        $count=$consulta->getResult();

        if(!empty($count)){
            return 1;
        }else{
            return 0;
        }
    }
}
