<?php

namespace Faltas\FaltasBundle\Repository;

/**
 * EstadoActaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstadoActaRepository extends \Doctrine\ORM\EntityRepository
{

	public function selectEstadosTabla()
    {
		$em=$this->getEntityManager();
		$dql="SELECT e.estado FROM FaltasFaltasBundle:EstadoActa e";

    	$consulta=$em->createQuery($dql);	

        return $consulta->getResult();

    }

    public function findAllMotivos()
    {
	    $qb = $this->createQueryBuilder('t');        
        $qb->orderBy('t.estado', 'ASC');
                 
        //return $qb->getQuery()->getResult();
        return $qb;
	}
}
