<?php

namespace Faltas\FaltasBundle\Repository;

/**
 * FajaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FajaRepository extends \Doctrine\ORM\EntityRepository
{	

	public function findAllFechaAsignacion()
    {
	    $qb = $this->createQueryBuilder('d');
        $qb->orderBy('d.fecha_asignacion', 'ASC');
        return $qb;
	}

	public function findAllAreas()
    {
	    $qb = $this->createQueryBuilder('d');
        $qb->orderBy('d.area', 'ASC');
        return $qb;
	}

	public function existeFajaxNumero($numero)
    {

    	$em=$this->getEntityManager();

    	$dql="SELECT f.numero
    		FROM FaltasFaltasBundle:Faja f
    		WHERE f.numero=:Numero";

    	$consulta=$em->createQuery($dql);
    	$consulta->setParameter('Numero',$numero);		
	    
	    $count=$consulta->getResult();

	    if(!empty($count)){
	    	return 1;
	    }else{
	    	return 0;
	    }
	}

	public function utilizadasEntreFecha($fechaInicial,$fechaFinal,$area)
	{
		$query = "SELECT count(DISTINCT checklist) FROM notificaciones.faja where fecha_inspeccion between '".$fechaInicial."' and '".$fechaFinal."' and id_area = ".$area;
		$stmt = $this->getEntityManager()->getConnection()->prepare($query);
		$stmt->execute();
		return $stmt->fetchAll();
	}
	
}
