<?php

namespace Faltas\FaltasBundle\Repository;

/**
 * TipoClausuraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoClausuraRepository extends \Doctrine\ORM\EntityRepository
{

		public function findAllTipoClausura()
    {
	    $qb = $this->createQueryBuilder('d');
        $qb->orderBy('d.tipoClausura', 'ASC');
        return $qb;
	}
}
